### ISSUE TITLE
If an opponent is selecting/choosing and then disconnects from the game, the other player's game will not end.

### ISSUE THREAD

**Issue by Hill-98** [Hastwell/Omukade.Cheyenne#10]
For example, if I use the Ability of Sylveon V to selecting a card, and then suddenly close the game, the other party's game will completely freeze.

I tried modifying the following code, and there was no problem after the modification.

https://github.com/Hastwell/Omukade.Cheyenne/blob/9c2d78b45e9f00d4ba24710d4ea951f61709aea8/Omukade.Cheyenne/GameServerCore.cs#L713

change `OperationType.TimeoutForceQuit` to `OperationType.Quit`

Is there a problem with TimeoutForceQuit because there is no timer?

**Comment by Hastwell** [comment]
`TimeoutForceQuit` is used to indicate the client has unwillingly left the game (connection issue/crash/etc). When a game ends for this reason, the opponent is shown that the opponent timed out/disconnected.

The game will refuse to let you start other actions/selection until you have finished your current selection, except for `Quit` which is always possible and always succeeds. It would seem that the `TimeoutForceQuit` sent on the disconnecting player's behalf is ignored for this reason. However, using `Quit` will show the opponent intentionally conceded when this may not necessarily be the case.

As a quick-fix, injecting `Quit` instead of `TimeoutForceQuit` will mitigate this issue with the aforementioned side-effect, but is probably not the correct long-term fix. Eg, end-of-turn timers would likely encounter similar problems, and I believe was at one point a problem even in the vanilla game.

**Comment by Hill-98** [comment]
I tested the same operation on the official server and it turns out that it works the same way.

But because there is an official timer, "opponent was inactive for too long" will be displayed after a certain period of time.

**Comment by Hastwell** [comment]
Fixed in 0b1e2975e6fc7ad942660f170c2b1a14fe3e3780 ; force-closing the game or otherwise causing a timeout condition to occur will now properly end the game and inform the remaining player they won due to "opponent was inactive for too long".
