### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by Hill-98** [Hastwell/Omukade.Cheyenne#2]
Error: `'GameStateOmukade.CopyState()': Inherited member 'GameState.CopyState()' is not marked virtual, abstract or override and cannot be overridden`

Is it possible to change `public override GameState CopyState()` to `public new GameState CopyState()`?

**Comment by Hastwell** [comment]
It looks like I had made an update to [ManualPAR](https://github.com/Hastwell/Omukade.ProcedualAssemblyRewriter) to apply specific patches for Live, but didn't update that documentation.

If you rerun ManualPAR with the (undocumented) flags `--fetch-update --rainier-specific`, it should produce assemblies where CopyState _is_ virtual and can be overridden by GameStateOmukade.

I cannot update GameStateOmukade.CopyState to be `new`; it has to be a virtual/overridden method so the game code will call the GameStateOmukade version instead of the normal GameState.

**Comment by Hill-98** [comment]
Good! The problem is solved!

**Comment by Hastwell** [comment]
Documentation has been updated. Thank you for reporting this!
